[workspace]
resolver = "2"

members = [
    "backend",
    "database",
    "database_bin",
    "druid-app",
#    "gtk-app",
    "frontend",
    "frontend_lib",
#    "qt-app",
#    "imgui",
    "relm4-app",
    "slint",
    "slint_lib",
]
