[workspace]
resolver = "2"

members = [
    "database",
    "database_bin",
    "gtk-app",
#    "frontend",
#    "frontend_lib",
#    "qt-app",
#    "imgui",
    "relm4-app",
    "slint",
    "slint_lib",
]
