import { StandardButton, Button , ListView, LineEdit, TextEdit , GroupBox} from "std-widgets.slint";
import { ImageButton } from "common.slint";
import { ChatRow, ChatRowData } from "chat.slint";
import { ChatMessageData, IncomingMessage, OutcomingMessage, PluginMessage } from "message.slint";

component InputSearch inherits Rectangle {
    //callback edit <=> input.edited;
    out property <bool> focused;

    input := LineEdit  {
        height: 40px;
        font-size: 14px;
        preferred-width: 100%;
        placeholder-text: "Search";
    }
}

export component InputText inherits Rectangle {
    in property <string> label;

    HorizontalLayout {
        width: 100%;
        padding-top: 10px;
        input := TextEdit {
            font-size: 16px;
            width: 100%;
            wrap: word-wrap;
        } 
    }
    
    HorizontalLayout {
        width: 100%;      
        padding-bottom: 20px;
        padding-top: 10px;
        visible: false;

        Text {
            text: input.text; 
            font-size: input.font-size;
            color: #d7d7d7;
            wrap: word-wrap;
        }
        Rectangle {
            width: 15px;
        }
    }    
 
    if (input.text == "") :
        HorizontalLayout {
            width: 100%;
            padding-right: 10px;        
            padding-bottom: 15px;
            padding-top: 10px;

            Text {
                width: 100%;
                height: 18px;
                text: label; 
                font-size: input.font-size;
                font-weight: 100;
                color: #7f7f7f;
            }
        }
     
}

export component PortalApp inherits Window {
    in property <[ChatRowData]> memory_chats: [
        { chat_name: "0 Some Chat Some", last_message_time_or_date: "00:01", last_message: "Some Chat Some Chat", unread_messages: 2 },
        { chat_name: "1 Some Chat Some", last_message_time_or_date: "00:01", last_message: "Some Chat Some Chat", unread_messages: 100 },
    ];
    in property <[ChatMessageData]> memory_messages: [
        { message_type: 0, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
        { message_type: 1, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
        { message_type: 2, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
    ];

    preferred-width: 100%;
    preferred-height: 100%;
    min-width: 900px;
    min-height: 600px;

    HorizontalLayout {

        VerticalLayout {
            width: 30%;

            HorizontalLayout {
                padding: 10px;
                spacing: 10px;

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                InputSearch {

                }              
            }

            ListView {
                height: 100%;
                for chat[i] in memory_chats : ChatRow {
                    chat_name: chat.chat_name;
                    last_message_time_or_date: chat.last_message_time_or_date;
                    last_message: chat.last_message;
                    unread_messages: chat.unread_messages;
                }
            }
        }

        Rectangle {
            width: 1px;
            background: #d4d4d4;
        }

        VerticalLayout {
            width: 70%; 

            ListView {
                for message[i] in memory_messages : HorizontalLayout {
                    if (message.message_type == 0) : IncomingMessage { message: message.message; }
                    if (message.message_type == 1) : OutcomingMessage { message: message.message; }
                    if (message.message_type == 2) : PluginMessage {}
                }
            }

            HorizontalLayout {
                width: 100%;
                height: 0%;
                padding-left: 10px;
                padding-right: 10px;
                padding-top: 10px;
                spacing: 10px;

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                InputText{
                    label: "Send message ....";
                }

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                Rectangle {
                    width: 10px;
                }

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }
            }
        }

        Rectangle {
            width: 100px;
            background: #d4d4d4;
        }

        
    }
}