import { RoundImage } from "common.slint";
import { StandardButton, Button , ListView, LineEdit  } from "std-widgets.slint";

export struct ChatRowData {
    chat_name: string,
    last_message_time_or_date: string,
    last_message: string,
    unread_messages: int,
}

export component ChatRow inherits Rectangle {
    in property <string> chat_name;
    in property <string> last_message_time_or_date;
    in property <string> last_message;
    in property <int> unread_messages;

    background: touch.has-hover ? #e7e7e7 :  #ff000000;
   
    HorizontalLayout {
        padding: 10px;
        spacing: 10px;
        alignment: center;

        RoundImage{
            image-url: @image-url("assets/face.png");
            size: 40px;
        }

        VerticalLayout {
            
            Text {                
                text: chat_name;
                font-weight: 700;
                color: #000;
                font-size: 14px;
                overflow: elide;
            } 

            Text {
                text: last_message;
                font-weight: 300;
                color: #9f9f9f;
                font-size: 14px;
                overflow: elide;
            } 
        }

        VerticalLayout {
            alignment: start;
            spacing: 5px;

            Text {
                horizontal-alignment: right;
                text: last_message_time_or_date;
            } 

            HorizontalLayout {
                alignment: end;
                Rectangle {
                    height: text.preferred-height + 5px;
                    width: text.preferred-width + 15px;
                    background: #a0a0a0;
                    border-radius: self.height / 2;
    
                    text := Text {
                        text: unread_messages >= 100 ? "99+" : unread_messages;
                        font-size: 14px;
                        color: #fff;
                    } 
                }   
            }
                     
        }
    }

    touch := TouchArea { 
        mouse-cursor: pointer;
    }
}