[package]
name = "ui_slint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0.0"
ui_slint_lib = { path = "../ui_slint_lib" }

[build-dependencies]
slint-build = "1.0.0"
