import { StandardButton, Button , ListView, LineEdit, TextEdit , GroupBox} from "std-widgets.slint";
import { ImageButton } from "common.slint";
import { ChatRow } from "chat.slint";
import { IncomingMessage, OutcomingMessage, PluginMessage } from "message.slint";

component InputSearch inherits Rectangle {
    callback edit <=> input.edited;
    out property <bool> focused;

    input := LineEdit  {
        height: 40px;
        font-size: 14px;
        preferred-width: 100%;
        placeholder-text: "Search";
    }
}

export component InputText inherits Rectangle { 

    in property <string> label;

    HorizontalLayout {
        width: 100%;
        padding-top: 10px;
        input := TextEdit {
            font-size: 16px;
            width: 100%;
            wrap: word-wrap;
        } 
    }
    
    HorizontalLayout {
        width: 100%;      
        padding-bottom: 20px;
        padding-top: 10px;
        visible: false;

        Text {
            text: input.text; 
            font-size: input.font-size;
            color: #d7d7d7;
            wrap: word-wrap;
        }
        Rectangle {
            width: 15px;
        }
    }    
 
    if(input.text == "") :  
        HorizontalLayout {
            width: 100%;
            padding-right: 10px;        
            padding-bottom: 15px;
            padding-top: 10px;

            Text {
                width: 100%;
                height: 18px;
                text: label; 
                font-size: input.font-size;
                font-weight: 100;
                color: #7f7f7f;
            }
        }
     
}

export component MyApp inherits Window {
    preferred-width: 100%;
    preferred-height: 100%;
    min-width: 900px;
    min-height: 600px;

    HorizontalLayout {

        VerticalLayout {
            width: 30%;
            
            HorizontalLayout {
                padding: 10px;
                spacing: 10px;

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                InputSearch {

                }              
                       
            }

            ListView { 
                height: 100%;  
                for i in 20 : ChatRow {
                    index: i;
                }
            }
        }

        Rectangle {
            width: 1px;
            background: #d4d4d4;
        }

        VerticalLayout {
            width: 70%; 

            ListView { 
                for i in [0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 2]
                    : HorizontalLayout {
                        if (i == 0) : IncomingMessage{}
                        if (i == 1) : OutcomingMessage{}
                        if (i == 2) : PluginMessage{}
                    }             
            }

            HorizontalLayout {
                width: 100%;
                height: 0%;
                padding-left: 10px;
                padding-right: 10px;
                padding-top: 10px;
                spacing: 10px;

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                InputText{
                    label: "Send message ....";
                }

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                Rectangle {
                    width: 10px;
                }

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }

                ImageButton {
                    image-url: @image-url("assets/xxx.svg");
                }
            }
        }       

        
    }
}