
export component RoundImage inherits Rectangle {
    in property <length> size;
    in property <image> image-url <=> img.source;
    height: size;
    width: size;
    border-radius: root.height / 2;
    clip: true;

    img := Image {
        height: size;
        width: size;
        image-fit: cover;
    }
}

export component ImageButton inherits Rectangle {
    in property <image> image-url <=> img.source;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    border-width: 1px;
    background: touch.pressed ? #bcbcbc : touch.has-hover ? #ececec :  #ff000000;
    height: 40px;
    width: 40px;
    padding: 10px;

    img := Image {
        height: 20px;
        width: 20px;
        image-fit: contain;
        colorize: #858585;
    }

    touch := TouchArea { }
}

export component TextButton inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #456;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;

    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
    }

    touch := TouchArea { }
}