[package]
name = "druid-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# druid = "0.8.3"
druid = { git = "https://github.com/linebender/druid.git", branch = "master" }
syn = { version = "1.0.109", features = ["extra-traits"] }