on: [push, pull_request]

name: Backend

env:
  CARGO_TERM_COLOR: always

jobs:
    test:
        name: Test postgres
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres
            env:
              POSTGRES_PASSWORD: postgres
              POSTGRES_USER: postgres
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 20s
              --health-timeout 15s
              --health-retries 120

        steps:
          - name: Checkout sources
            uses: actions/checkout@v2

          - name: Install stable toolchain
            uses: actions-rs/toolchain@v1
            with:
              profile: minimal
              toolchain: stable
              override: true

          - name: Test postgres connection
            run: psql postgres://postgres:postgres@localhost:5432/postgres -c 'SELECT 1;'

          - name: Install dependencies and set up database
            run: |
              cargo install sqlx-cli

          - name: Run migrations
            env:
              DATABASE_URL: postgres://postgres:postgres@127.0.0.1/postgres
            working-directory: ./backend
            run: sqlx migrate run
            
          - name: Build project
            working-directory: ./backend
            run: cargo build
            
          - name: Run cargo tests
            env:
              DATABASE_URL: postgres://postgres:postgres@127.0.0.1/postgres
            working-directory: ./backend
            run: cargo test
