name: Build and upload docker image
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Build and upload docker image' 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    environment:
      name: production

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Get latest tag
#       id: latest_tag
#       run: echo ::set-output name=latest_tag::$(git describe --tags --abbrev=0)

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          sturivnyi/rust-wasm:latest
#          sturivnyi/rust-wasm:${{ steps.latest_tag.outputs.latest_tag }}
