name: Run cargo tests
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  cargo_test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies and set up database
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libgtk-4-dev libpq-dev
        cargo install sqlx-cli

    - name: Run Rustfmt
      run: |
        rustup component add rustfmt
        cargo fmt --all --check

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@127.0.0.1/postgres
      working-directory: ./database
      run: sqlx migrate run

    - name: Build project
      run: cargo build

    - name: Run Clippy
      run: |
        rustup component add clippy
        cargo clippy --no-deps

    - name: Run cargo tests
      env:
        DATABASE_URL: postgres://postgres:postgres@127.0.0.1/postgres
      run: cargo test
